// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindowsForms.DataContext;

#nullable disable

namespace WindowsForms.Migrations
{
    [DbContext(typeof(CineContext))]
    [Migration("20250702204533_IncioProyecto")]
    partial class IncioProyecto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WindowsForms.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eliminado = false,
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Eliminado = false,
                            Nombre = "Brasil"
                        },
                        new
                        {
                            Id = 3,
                            Eliminado = false,
                            Nombre = "Chile"
                        },
                        new
                        {
                            Id = 4,
                            Eliminado = false,
                            Nombre = "España"
                        },
                        new
                        {
                            Id = 5,
                            Eliminado = false,
                            Nombre = "México"
                        },
                        new
                        {
                            Id = 6,
                            Eliminado = false,
                            Nombre = "Estados Unidos"
                        },
                        new
                        {
                            Id = 7,
                            Eliminado = false,
                            Nombre = "Francia"
                        },
                        new
                        {
                            Id = 8,
                            Eliminado = false,
                            Nombre = "Italia"
                        },
                        new
                        {
                            Id = 9,
                            Eliminado = false,
                            Nombre = "Alemania"
                        },
                        new
                        {
                            Id = 10,
                            Eliminado = false,
                            Nombre = "Japón"
                        });
                });

            modelBuilder.Entity("WindowsForms.Models.Pelicula", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("_id")
                        .HasColumnType("longtext");

                    b.Property<double>("calificacion")
                        .HasColumnType("double");

                    b.Property<int>("duracion")
                        .HasColumnType("int");

                    b.Property<string>("portada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Eliminado = false,
                            calificacion = 8.1999999999999993,
                            duracion = 129,
                            portada = "https://image.tmdb.org/t/p/w500/secreto.jpg",
                            titulo = "El secreto de sus ojos"
                        },
                        new
                        {
                            id = 2,
                            Eliminado = false,
                            calificacion = 8.5999999999999996,
                            duracion = 130,
                            portada = "https://image.tmdb.org/t/p/w500/ciudad.jpg",
                            titulo = "Ciudad de Dios"
                        },
                        new
                        {
                            id = 3,
                            Eliminado = false,
                            calificacion = 8.0999999999999996,
                            duracion = 154,
                            portada = "https://image.tmdb.org/t/p/w500/amores.jpg",
                            titulo = "Amores Perros"
                        },
                        new
                        {
                            id = 4,
                            Eliminado = false,
                            calificacion = 8.5999999999999996,
                            duracion = 116,
                            portada = "https://image.tmdb.org/t/p/w500/vida.jpg",
                            titulo = "La vida es bella"
                        },
                        new
                        {
                            id = 5,
                            Eliminado = false,
                            calificacion = 8.1999999999999993,
                            duracion = 118,
                            portada = "https://image.tmdb.org/t/p/w500/laberinto.jpg",
                            titulo = "El laberinto del fauno"
                        },
                        new
                        {
                            id = 6,
                            Eliminado = false,
                            calificacion = 8.5,
                            duracion = 112,
                            portada = "https://image.tmdb.org/t/p/w500/intouchables.jpg",
                            titulo = "Intouchables"
                        },
                        new
                        {
                            id = 7,
                            Eliminado = false,
                            calificacion = 8.5999999999999996,
                            duracion = 125,
                            portada = "https://image.tmdb.org/t/p/w500/spirited.jpg",
                            titulo = "Spirited Away"
                        },
                        new
                        {
                            id = 8,
                            Eliminado = false,
                            calificacion = 8.5,
                            duracion = 132,
                            portada = "https://image.tmdb.org/t/p/w500/parasite.jpg",
                            titulo = "Parasite"
                        },
                        new
                        {
                            id = 9,
                            Eliminado = false,
                            calificacion = 8.8000000000000007,
                            duracion = 142,
                            portada = "https://image.tmdb.org/t/p/w500/forrest.jpg",
                            titulo = "Forrest Gump"
                        },
                        new
                        {
                            id = 10,
                            Eliminado = false,
                            calificacion = 8.6999999999999993,
                            duracion = 148,
                            portada = "https://image.tmdb.org/t/p/w500/inception.jpg",
                            titulo = "Inception"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
